# Copyright 2018 The Kubernetes Authors.
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for unet3d-loading-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: ubuntu:24.04
bucketName: gke-dlio-test-data
resultsBucketName: jaimebz-bucket
scenario: local-ssd
# nodeType: n2-standard-96

# FIO container resource limits. Set according to machine type, goal is usually to schedule only one pod per node in FIO.
resourceLimits:
  cpu: 100
  memory: 400Gi

fio:
  # File configs
  fileSize: 64K
  blockSize: 64K

  # Read behavior configs
  readType: read
  direct: 0 # Skip page cache
  
  # Thread configs
  numJobs: 50 # Number of threads
  filesPerThread: "20000"

  # Epoch configs
  epochs: 1 # Number of reruns in same instance/pod.
  pauseBetweenEpochs: 20

gcsfuse:
  volumeAttributes:
    skipCSIBucketAccessCheck: "false"
    gcsfuseMetadataPrefetchOnMount: "false"
    gcsfuseLoggingSeverity: "trace"
    disableMetrics: "true"
  mountOptions: implicit-dirs
